parameters:
    database_driver:                      pdo_mysql
    database_host:                        db
    database_name:                        akeneo
    database_user:                        akeneo
    database_password:                    nTLTpG7MrhtWF7lnOZgeQ9b1WHkTyTv7
    locale:                               en
    secret:                               38izTdNsAzNEZxzVmVLjmzPP9RTR5LAL
    product_index_name:                   akeneo_pim_product
    product_model_index_name:             akeneo_pim_product_model
    product_and_product_model_index_name: akeneo_pim_product_and_product_model
    index_hosts:                          'elastic: 9200'
    #installer_data: PimInstallerBundle:minimal
    installer_data: PimInstallerBundle:icecat_demo_dev
    mailer_host: mailhog
    mailer_port: 1025
